# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rake db:seed (or created alongside the db with db:setup).
#
# Examples:
#
#   cities = City.create([{ name: 'Chicago' }, { name: 'Copenhagen' }])
#   Mayor.create(name: 'Emanuel', city: cities.first)
Outline.create(number: '1', title: 'How Well Do You Know God?')
Outline.create(number: '2', title: 'Will You Be a Survivor of the Last Days?')
Outline.create(number: '3', title: 'Serving With Jehovah’s Unified Organization')
Outline.create(number: '4', title: 'Evidence of God in the World Around Us')
Outline.create(number: '5', title: 'Family Life That Warms the Heart')
Outline.create(number: '6', title: 'The Flood of Noah’s Day Has Meaning for Us')
Outline.create(number: '7', title: 'Mercy, a Dominant Quality of True Christians')
Outline.create(number: '8', title: 'Living, Not for Self, But to Do God’s Will')
Outline.create(number: '9', title: 'Never Become Dull in Your Hearing')
Outline.create(number: '10', title: 'Conducting Ourselves Honestly at All Times')
Outline.create(number: '11', title: '“No Part of the World”—In Imitation of Christ')
Outline.create(number: '12', title: 'Respect for Authority Is a Safeguard for You')
Outline.create(number: '13', title: 'A Godly View of Sex and Marriage')
Outline.create(number: '14', title: 'A Clean People Honors Jehovah')
Outline.create(number: '15', title: 'As Christians, We Care About Other People')
Outline.create(number: '16', title: 'Keep Growing in Your Relationship With God')
Outline.create(number: '17', title: 'Glorifying God With All We Have')
Outline.create(number: '18', title: 'Are You Really Making Jehovah Your Stronghold?')
Outline.create(number: '19', title: 'Your Future—How Can It Be Known?')
Outline.create(number: '20', title: 'Is It Time for God to Rule the World?')
Outline.create(number: '21', title: 'How Do You Fit Into the Kingdom Arrangement?')
Outline.create(number: '22', title: 'Are You Content With Jehovah’s Provisions?')
Outline.create(number: '23', title: 'Life Does Have a Purpose')
Outline.create(number: '24', title: 'What God’s Rulership Can Do for Us')
Outline.create(number: '25', title: 'Resisting the Spirit of the World')
Outline.create(number: '26', title: 'Does God Count You Personally Important?')
Outline.create(number: '27', title: 'Getting Marriage Off to a Good Start')
Outline.create(number: '28', title: 'Show Respect and Love in Your Marriage')
Outline.create(number: '29', title: 'Responsibilities and Rewards of Parenthood')
Outline.create(number: '30', title: 'Communication—Within the Family and With God')
Outline.create(number: '31', title: 'Happy Though Hungry—How Can It Be?')
Outline.create(number: '32', title: 'Coping With Life’s Anxieties')
Outline.create(number: '33', title: 'What Is Behind the Spirit of Rebellion?')
Outline.create(number: '34', title: 'Are You “Marked” for Survival?')
Outline.create(number: '35', title: 'Can You Live Forever? Will You?')
Outline.create(number: '36', title: 'Is This Life All There Is?')
Outline.create(number: '37', title: 'Decide Now for Divine Rulership')
Outline.create(number: '38', title: 'Act Wisely as the End Draws Near')
Outline.create(number: '39', title: 'Be Confident of Divine Victory!')
Outline.create(number: '40', title: 'What the Near Future Holds!')
Outline.create(number: '41', title: '“Stand Still and See the Salvation of Jehovah”')
Outline.create(number: '42', title: 'How the Kingdom of God Affects You')
Outline.create(number: '43', title: 'Are You Doing What God Requires of You?')
Outline.create(number: '44', title: 'Keep Seeking God’s Kingdom')
Outline.create(number: '45', title: 'Follow the Way to Life')
Outline.create(number: '46', title: 'Maintain Your Confidence Firm to the End')
Outline.create(number: '47', title: '“Have Faith in the Good News”')
Outline.create(number: '48', title: 'Meeting the Test of Christian Loyalty')
Outline.create(number: '49', title: 'A Cleansed Earth—Will You Live to See It?')
Outline.create(number: '50', title: 'Decisions You Face—How Will You Make Them?')
Outline.create(number: '51', title: 'Is the Truth Transforming Your Life?')
Outline.create(number: '52', title: 'Who Is Your God?')
Outline.create(number: '53', title: 'Does Your Thinking Agree With God’s?')
Outline.create(number: '54', title: 'Build Your Faith in Man’s Maker')
Outline.create(number: '55', title: 'What Kind of Name Are You Making With God?')
Outline.create(number: '56', title: 'Into the New World Under Christ’s Leadership')
Outline.create(number: '57', title: 'Bearing Up Under Persecution')
Outline.create(number: '58', title: 'How Should You Serve God?')
Outline.create(number: '59', title: 'You Will Reap What You Sow')
Outline.create(number: '60', title: 'How Purposeful Is Your Life?')
Outline.create(number: '61', title: 'On Whose Promises Do You Rely?')
Outline.create(number: '62', title: 'The Only Cure for Sick Mankind')
Outline.create(number: '63', title: 'Do You Have the Evangelizing Spirit?')
Outline.create(number: '64', title: 'Lovers of Pleasure or Lovers of God?')
Outline.create(number: '65', title: 'Finding Honor and Joy in God’s Ministry')
Outline.create(number: '66', title: 'Slave for the Master of the Harvest')
Outline.create(number: '67', title: 'Taking Time to Meditate on Spiritual Things')
Outline.create(number: '68', title: 'Do You Harbor Resentment, or Do You Forgive?')
Outline.create(number: '69', title: 'Renewing the Spirit of Self-Sacrifice')
Outline.create(number: '70', title: 'Make Jehovah Your Confidence')
Outline.create(number: '71', title: 'How to Keep Spiritually Awake')
Outline.create(number: '72', title: 'Love Identifies the True Christian Congregation')
Outline.create(number: '73', title: 'Acquiring a Heart of Wisdom')
Outline.create(number: '74', title: 'Jehovah’s Eyes Are Upon Us')
Outline.create(number: '75', title: 'Do You Recognize Jehovah’s Sovereignty in Your Personal Life?')
Outline.create(number: '76', title: 'Bible Principles—Can They Help Us to Cope With Today’s Problems?')
Outline.create(number: '77', title: 'Follow the Course of Hospitality')
Outline.create(number: '78', title: 'Serve Jehovah With a Joyful Heart')
Outline.create(number: '79', title: 'Friendship With God, Friendship With the World —Which Will You Choose?')
Outline.create(number: '80', title: 'Does Your Hope Rest on Science or the Bible?')
Outline.create(number: '81', title: 'Who Are Qualified as Ministers of God?')
Outline.create(number: '82', title: 'Jehovah and Christ—Are They Part of a Trinity?')
Outline.create(number: '83', title: 'Religion’s Time of Judgment')
Outline.create(number: '84', title: 'Will You Escape This World’s Destiny?')
Outline.create(number: '85', title: 'Good News in a Violent World')
Outline.create(number: '86', title: 'Prayers That Are Heard by God')
Outline.create(number: '87', title: 'What Is Your Relationship With God?')
Outline.create(number: '88', title: 'Why Live by Bible Standards?')
Outline.create(number: '89', title: 'Come, You Who Thirst for the Truth!')
Outline.create(number: '90', title: 'Reach Out for the Real Life!')
Outline.create(number: '91', title: 'The Messiah’s Presence and His Rule')
Outline.create(number: '92', title: 'Religion’s Role in World Affairs')
Outline.create(number: '93', title: '“Acts of God”—How Do You View Them?')
Outline.create(number: '94', title: 'True Religion Meets the Needs of Human Society')
Outline.create(number: '95', title: 'The Bible’s View of Spiritistic Practices')
Outline.create(number: '96', title: 'False Religion’s End Is Near')
Outline.create(number: '97', title: 'Remaining Blameless Amid a Crooked Generation')
Outline.create(number: '98', title: 'Keep Clean From Worldly Defilements')
Outline.create(number: '99', title: 'Why You Can Trust the Bible')
Outline.create(number: '100', title: 'True Friendship With God and Neighbor')
Outline.create(number: '101', title: 'Jehovah—The Grand Creator')
Outline.create(number: '102', title: 'Paying Attention to the Prophetic Word')
Outline.create(number: '103', title: 'You Can Find Joy in Serving God')
Outline.create(number: '104', title: 'Parents—Are You Building With Fire-Resistant Materials?')
Outline.create(number: '105', title: 'Gaining Comfort in All Our Tribulations')
Outline.create(number: '106', title: 'Ruining the Earth Brings Divine Retribution')
Outline.create(number: '107', title: 'Hold a Good Conscience in a Sinful World')
Outline.create(number: '108', title: 'Overcoming Fear of the Future')
Outline.create(number: '109', title: 'The Kingdom of God Is Near')
Outline.create(number: '110', title: 'God Comes First in Successful Family Life')
Outline.create(number: '111', title: 'What Does the Healing of the Nations Accomplish?')
Outline.create(number: '112', title: 'How to Express Love in a Lawless World')
Outline.create(number: '113', title: 'How Can Youths Cope With Today’s Crisis?')
Outline.create(number: '114', title: 'Appreciating Marvels of God’s Creation')
Outline.create(number: '115', title: 'How to Protect Ourselves From Satan’s Snares')
Outline.create(number: '116', title: 'Choose Your Associates Wisely!')
Outline.create(number: '117', title: 'How to Conquer Evil With Good')
Outline.create(number: '118', title: 'Looking at Youths From Jehovah’s Standpoint')
Outline.create(number: '119', title: 'Christian Separateness From the World —Why Beneficial')
Outline.create(number: '120', title: 'Why Submit to God’s Rulership Now')
Outline.create(number: '121', title: 'A Worldwide Brotherhood Saved From Calamity')
Outline.create(number: '122', title: 'Global Peace—From What Source?')
Outline.create(number: '123', title: 'Why Christians Must Be Different')
Outline.create(number: '124', title: 'Basis for Confidence in the Bible’s Divine Authorship')
Outline.create(number: '125', title: 'Why Mankind Needs a Ransom')
Outline.create(number: '126', title: 'Who Can Be Saved?')
Outline.create(number: '127', title: 'What Happens When We Die?')
Outline.create(number: '128', title: 'Is Hell Really a Place of Fiery Torment?')
Outline.create(number: '129', title: 'Is the Trinity a Scriptural Teaching?')
Outline.create(number: '130', title: 'The Earth Will Remain Forever')
Outline.create(number: '131', title: 'Is There Really a Devil?')
Outline.create(number: '132', title: 'The Resurrection—Victory Over Death!')
Outline.create(number: '133', title: 'The Origin of Humans—Does It Matter What You Believe?')
Outline.create(number: '134', title: 'Should Christians Keep the Sabbath?')
Outline.create(number: '135', title: 'The Sacredness of Life and Blood')
Outline.create(number: '136', title: 'Does God Approve of the Use of Images in Worship?')
Outline.create(number: '137', title: 'Did the Miracles of the Bible Really Happen?')
Outline.create(number: '138', title: 'Live With Soundness of Mind in a Depraved World')
Outline.create(number: '139', title: 'Godly Wisdom in a Scientific World')
Outline.create(number: '140', title: 'Jesus Christ—Earth’s New Ruler')
Outline.create(number: '141', title: 'Human Creation’s Groaning—When Will It End?')
Outline.create(number: '142', title: 'Why Take Refuge in Jehovah')
Outline.create(number: '143', title: 'Trust in the God of All Comfort')
Outline.create(number: '144', title: 'A Loyal Congregation Under Christ’s Leadership')
Outline.create(number: '145', title: 'Who Is Like Jehovah Our God?')
Outline.create(number: '146', title: 'Use Education to Praise Jehovah')
Outline.create(number: '147', title: 'Trust in Jehovah’s Saving Power')
Outline.create(number: '148', title: 'Do You Share God’s View of Life?')
Outline.create(number: '149', title: 'Are You Walking With God?')
Outline.create(number: '150', title: 'How Real Is God to You?')
Outline.create(number: '151', title: 'Jehovah Is “a Secure Height” for His People')
Outline.create(number: '152', title: 'The Real Armageddon—Why? When?')
Outline.create(number: '153', title: 'Keep Close in Mind the “Fear-Inspiring Day”!')
Outline.create(number: '154', title: 'Human Rule—Weighed in the Balance')
Outline.create(number: '155', title: 'Has Babylon’s Judgment Hour Arrived?')
Outline.create(number: '156', title: 'Judgment Day—A Time of Fear or Hope?')
Outline.create(number: '157', title: 'How True Christians Adorn Divine Teaching')
Outline.create(number: '158', title: 'Be Courageous, and Trust in Jehovah')
Outline.create(number: '159', title: 'Finding Security in a Dangerous World')
Outline.create(number: '160', title: 'Safeguard Your Christian Identity!')
Outline.create(number: '161', title: 'Why Did Jesus Suffer and Die?')
Outline.create(number: '162', title: 'Deliverance From a World of Darkness')
Outline.create(number: '163', title: 'Why Fear the True God?')
Outline.create(number: '164', title: 'Is God Still in Control?')
Outline.create(number: '165', title: 'Whose Values Do You Cherish?')
Outline.create(number: '166', title: 'Facing the Future With Faith and Courage')
Outline.create(number: '167', title: 'Act Wisely in a Senseless World')
Outline.create(number: '168', title: 'You Can Feel Safe in This Troubled World!')
Outline.create(number: '169', title: 'Why Be Guided by the Bible?')
Outline.create(number: '170', title: 'Who Is Qualified to Rule Mankind?')
Outline.create(number: '171', title: 'You Can Enjoy Life in Peace Now—And Forever!')
Outline.create(number: '172', title: 'What Is Your Standing With God?')
Outline.create(number: '173', title: 'Is There a True Religion From God’s Standpoint?')
Outline.create(number: '174', title: 'God’s New World—Who Will Qualify to Enter?')
Outline.create(number: '175', title: 'What Marks the Bible as Authentic?')
Outline.create(number: '176', title: 'Real Peace and Security—When?')
Outline.create(number: '177', title: 'Where Can You Get Help in Times of Distress?')
Outline.create(number: '178', title: 'Walk in the Way of Integrity')
Outline.create(number: '179', title: 'Reject Worldly Fantasies, Pursue Kingdom Realities')
Outline.create(number: '180', title: 'The Resurrection—Why That Hope Should Be Real to You')
Outline.create(number: '181', title: 'Is It Later Than You Think?')
Outline.create(number: '182', title: 'What God’s Kingdom Is Doing for Us Now')
Outline.create(number: '183', title: 'Turn Your Eyes Away From Worthless Things!')

